services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./internal
        - action: rebuild
          path: ./pkg
        - action: rebuild
          path: ./main.go
    environment:
      DB_HOST: database:3306
      DB_NAME: breadzilla
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - 3000:3000
    restart: always

  database:
    build:
      context: .
      dockerfile: ./Dockerfile.db
    environment:
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: breadzilla
    ports:
      - 3306:3306
    volumes:
      - ./.data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 3m
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always