services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    develop:
      watch:
        - action: rebuild
          path: ./internal
        - action: rebuild
          path: ./pkg
        - action: rebuild
          path: ./main.go
    environment:
      DB_HOST: database:3306
      DB_NAME: breadzilla
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - 3000:3000
    restart: always
  database:
    build:
      context: .
      dockerfile: ./Dockerfile.db
    restart: always
    environment:
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: breadzilla
    volumes:
      - ./.data:/var/lib/mysql
    ports:
      - 3306:3306